### ISSUE TITLE
Use a default name for snapshots

### ISSUE THREAD

**Issue by salcode** [binarygary/db-checkpoint#1]
This plugin provides some great functionality but I think siloing the snapshots by name is excessive.

I'd rather run

```
wp snapshot set
```

// do whatever I do here to muck up the database

```
wp snapshot get
```

You could still leave the name parameter as optional but honestly I'm not sure it is worth the additional complexity.  Database backups are pretty easy with **wp-cli** and the use case I see here is the quick rollback.

**Comment by binarygary** [comment]
That's a good point and one I was thinking about late last night.  
The likelihood that a user will need 2 distinct DB versions to roll back to during active development presents a pretty complex scenario...one that better fits the built in db command in WP-CLI

**Comment by binarygary** [comment]
Changes name attribute to optional.
Also looking at changing the command so it's shorter to type.
