### ISSUE TITLE
How is wp snapshot list <name> used?

### ISSUE THREAD

**Issue by salcode** [binarygary/db-checkpoint#2]
I understand this will list the snapshots that have been created but we don't have any control over which one we roll back to, correct?  Because of this, I don't see the use of `wp snapshot list <name>`

Something like `wp snapshot which` might be more helpful, showing us what file will be used when running `wp snapshot get`

**Comment by binarygary** [comment]
I'm removing the listing functionality for the time being.  
Logically this package needs to deal in absolutes...multiple checkpoints for each name could be problematic.  
I'll leave a todo to circle back around to this feature.
