### ISSUE TITLE
Change command to more specific name than snapshot

### ISSUE THREAD

**Issue by salcode** [binarygary/db-checkpoint#3]
In my experience a Snapshot of a website usually includes both the database **and** the files.  I'm not arguing the files should be backed up here but changing to **dbsnapshot** might make it clearer.

```
wp dbsnapshot set
```

**Comment by binarygary** [comment]
Another good point...that command is a bit misleading.

**Comment by binarygary** [comment]
commands are tentatively 

wp dbsnap
wp dbsnapback
