### ISSUE TITLE
Make snapshot names more descriptive?

### ISSUE THREAD

**Issue by salcode** [binarygary/db-checkpoint#4]
I like how the file generated by `wp db export` uses the database name.

Beyond the database name, I really like having the date and time as part of the database backups.

~~e.g. `20161012-1539-example.sql`~~
e.g. `example-20161012-1539.sql`

**Comment by binarygary** [comment]
Currently the file name includes the timestamp of db save.
My intent for the info command is to actually parse that out for those of us that don't read timestamps like a clock.

**Comment by salcode** [comment]
I'd argue for doing the parsing to create the filename and thus not have to worry about it later.  

Modification to my original suggestion, if you start the filename with the database name, it would probably make it easier to find your file.

```
example-20161012-1551.sql
```

**Comment by binarygary** [comment]
This is pretty logical.  
My preferred nomenclature is 
_snapshotname_.timestamp.sql 
example: test.20161013-0205.sql
