### ISSUE TITLE
This would make a great package

### ISSUE THREAD

**Issue by salcode** [binarygary/db-checkpoint#5]
While I'd like to use this command, I'm not jazzed about installing a plugin on each site I want to use it on.

I imagine it would generally be used on my local install so a package would be more convenient so I always have access to it without installing anything.

https://wp-cli.org/commands/package/

**Comment by binarygary** [comment]
...and submitted...

**Comment by binarygary** [comment]
https://github.com/wp-cli/package-index/blob/master/repositories.txt

**Comment by binarygary** [comment]
And now it is! 
`wp package install binarygary/db-checkpoint`
 should get you there.
