### ISSUE TITLE
When loaded as a package instead of a plugin wp_upload_dir isn't available.

### ISSUE THREAD

**Issue by binarygary** [binarygary/db-checkpoint#8]
Error: Call to undefined function wp_upload_dir() in /Users/garykovar/.wp-cli/packages/vendor/binarygary/db-checkpoint/db-checkpoint.php on line 104

**Comment by binarygary** [comment]
This was related to @when
It turns out if you run pre_wp_load the WP functions will not be available. ¯_(ツ)_/¯

**Comment by danielbachhuber** [comment]
> It turns out if you run pre_wp_load the WP functions will not be available.

Yep, `before_wp_load` is appropriately named ;)

**Comment by binarygary** [comment]
In this case it was my fault for starting with copy pasta of the 3rd param array from http://wp-cli.org/docs/commands-cookbook/ in the add_command.

It might help to change that @when to init as I would guess a few people will probably make the same mistake.

**Comment by danielbachhuber** [comment]
> It might help to change that @when to init as I would guess a few people will probably make the same mistake.

`init` isn't a valid hook. `@when` refers to [several named WP-CLI hooks](http://wp-cli.org/docs/internal-api/wp-cli-add-hook/)

**Comment by binarygary** [comment]
Great example of me wanting to view this in the lens of a plugin. lol
BRB...gotta push an update!
